# Copyright 2020 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.

language: node_js

os:
  - "windows"

node_js:
  - "10"
  - "12"
  - "14"

arch:
  - amd64
  - arm64

env:
  - TEST_DIR=projects/worker-animal-pictures
  - TEST_DIR=projects/worker-basic
  
services: 
  - docker

install:
  - npm install -g @adobe/aio-cli
  - aio plugins:install @adobe/aio-cli-plugin-asset-compute
  - aio info

before_script:
  - |
    (
      if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
        choco install docker-desktop --pre 
        choco install docker-cli

        source .bash_profile
        source ~/.bashrc

        $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchDaemon
      fi
      exit 0
    )

script:
  - cd $TEST_DIR && npm install && npm test