operations:
  workerProcess:
    - type: action
      impl: dx-asset-compute-worker-1/worker
hooks:
  post-app-run: adobe-asset-compute devtool
  test: adobe-asset-compute test-worker
actions: actions
runtimeManifest:
  packages:
    dx-asset-compute-worker-1:
      license: Apache-2.0
      actions:
        worker-pdf-services:
          function: actions/worker-pdf-services/index.js
          inputs:
            docCloudClientId: ${DOC_CLOUD_CLIENT_ID}
            docCloudClientSecret: ${DOC_CLOUD_CLIENT_SECRET}
            docCloudOrgId: ${DOC_CLOUD_ORG_ID}
            docCloudAccountId: ${DOC_CLOUD_ACCOUNT_ID}
            docCloudPrivateKey: ${DOC_CLOUD_PRIVATE_KEY_BASE64}
          web: 'yes'
          runtime: 'nodejs:14'
          limits:
            concurrency: 1
            timeout: 600000
            memory: 512
          annotations:
            require-adobe-auth: true
